[package]
name = "gallery"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
iced = { version = "0.15.0-dev", git = "https://github.com/iced-rs/iced", branch = "master", default-features = false, features = ["wgpu", "web-colors", "thread-pool", "svg"] }
moonveil = { path = "../.." }
